## 1.1 构建
### 1.1.1 墙 
<img src="../img/101/Wall.png" width="48" />

#### 1.1.1.1 创建墙体 
<img src="../img/101/Wall.png" width="48" />

#####  API-1：<font color=gray>(2016~2023)</font>
```CSharp 
 Wall Create(
	Document document,//当前的项目文档
	Curve curve,//墙体的基线
	ElementId levelId,//墙体所在标高
	bool structural//是否为结构墙
)
```

##### 示例1
```CSharp
public Wall CreateWallUsingCurve(Autodesk.Revit.DB.Document document, Level level)
{
    XYZ start = new XYZ(0, 0, 0);
    XYZ end = new XYZ(10, 10, 0);
    Line geomLine = Line.CreateBound(start, end);
    return Wall.Create(document, geomLine, level.Id, true);
}
```
##### 备注1
>没有指定WallType,所以采用默认墙类型


##### API-2:(2016~2023)
```csharp
 Wall Create(
	Document document,//当前的项目文档
	IList<Curve> profile,//墙体的轮廓
	bool structural//是否为结构墙
)
```
##### 示例2
```csharp

```

##### 备注2
>通过墙体立面轮廓线来创建墙体，多数为不规则墙体（非矩形）

#### 1.1.1.2 创建分隔条
 <img src="../img/101/CreateWallSweep.png" width="45" />

##### API
```csharp
WallSweep Create(
	Wall wall,
	ElementId wallSweepType,
	WallSweepInfo wallSweepInfo
)
```
##### 示例
```CSharp
 	var reference = uiSel.PickObject(Autodesk.Revit.UI.Selection.ObjectType.Element, "Pick wall");
    var wall = doc.GetElement(reference) as Wall;
    ElementType wallSweepType = new FilteredElementCollector(doc)
        .OfCategory(BuiltInCategory.OST_Cornices)
        .WhereElementIsElementType()
        .Cast<ElementType>().FirstOrDefault();
    if (wallSweepType != null)
    {
        var wallSweepInfo = new WallSweepInfo(WallSweepType.Sweep, false);
        wallSweepInfo.Distance = 2;
        using (Transaction transaction = new Transaction(doc))
        {
            transaction.Start("create wall sweep");
            WallSweep.Create(wall, wallSweepType.Id, wallSweepInfo);
            transaction.Commit();
        }
    }
```

#### 1.1.1.3 修改墙体 

##### API-1：不/允许连接<font color=gray>(2016~2023)</font>
```CSharp
//设置墙体不允许连接
WallUtils.DisallowWallJoinAtEnd(
    Wall wall,
    int end//0:起点 1:终点
)
//设置墙体允许连接
WallUtils.AllowWallJoinAtEnd(
    Wall wall,
    int end//0:起点 1:终点
)
//判断墙体是否允许连接
wallutils.IsWallJoinAllowedAtEnd(
    Wall wall,
    int end//0:起点 1:终点
)
``` 

##### API-2：修改墙连接在一起的方式(平接、斜接、方接) <font color=gray>(2016~2023)</font>
```CSharp
public enum JoinType {
    None,//没有连接类型
    Abut，//平接
    Miter,//斜接
    SquareOff,//方接
    Extension
}
```

##### 示例2 
```CSharp
public void SetWallJoinType(Wall wall,int end,JoinType joinType)
{
    var locationCurve = wall.Location as LocationCurve;
    locationCurve.set_JoinType(end,joinType);
}
```

##### API-3：获取设置墙体的层次信息 <font color=gray>(2016~2023)</font>
```CSharp
public class CompoundStructure{
    
}

public class CompoundStructureLayer {

}
```

##### 示例3
```CSharp
public void SetWallLayerThickness(WallType wallType,double thickness)
{
    var compoundStructure = wallType.GetCompoundStructure();
    var layers = compoundStructure.GetLayers();
    foreach (var layer in layers)
    {
        
    }
}
```
##### 备注 
>复合结构由有序层的集合组成，墙从外部到内部，或从上到下进行地板、屋顶或天花板。这些图层的属性决定了厚度、材料和相关墙体、楼板、屋顶或天花板的整体结构的功能。层可以通过GetLayers方法访问，并使用SetLayer完全替换。层也可以使用“图层索引”单独访问和修改，该索引是范围[0， LayerCount)中的值标识结构中的层。结构支持“核心层”和“壳层”的概念。有两个图层索引标识其中，核心层和壳层之间的边界出现在层列表中。壳层和核心层之间的边界可以使用 GetFirstCoreLayerIndex、GetLastCoreLayerIndex、GetCoreBoundaryLayerIndex(ShellLayerType)或GetNumberOfShellLayers(ShellLayerType)进行识别。核心层边界可以使用SetNumberOfShellLayers(ShellLayerType,Int32)进行更改。复合结构可以是垂直复合的。如果IsVerticallyCompound为假，复合结构描述了一系列平行层，每个层都有指定的宽度、功能、材料和其他属性。如果IsVerticallyCompound为 true（这应该仅适用于分配给墙的复合结构），则不同高程的水平截面可能具有不同的分层结构。在这种情况下，该结构通过矩形描述垂直截面它被划分为多边形区域，其边都是垂直或水平段。这些区域与复合结构中的层通过一一映射相关联，该索引确定该区域的属性。

##### API-4：修改墙体的朝向 <font color=gray>(2016~2023)</font>
```CSharp
wall.Flip();
```

### 1.1.2 门 <img src="../img/101/Door.png" width="48" />
##### API-1：<font color=gray>(2016~2023)</font>
```CSharp 
 FamilyInstance NewFamilyInstance(
	XYZ location,
	FamilySymbol symbol,
	Element host,
	StructuralType structuralType
)
```
##### 

##### 示例
```CSharp
Wall CreateWallWithWindows(Autodesk.Revit.DB.Document document, Level level)
{
    // 创建一片墙
    // 构建一条墙的基线
    XYZ start = new XYZ(0, 0, 0);
    XYZ end = new XYZ(10, 10, 0);
    Line wallLine = Line.CreateBound(start, end);

    // 以基线的方式创建墙体
    Wall newWall = Wall.Create(document, wallLine, level.Id, true);

    // 找到一个门的族模型
    FilteredElementCollector doorCollector = new FilteredElementCollector(document);
    IList<Element> doorTypes = doorCollector.OfCategory(BuiltInCategory.OST_Doors).WhereElementIsElementType().ToElements();
    FamilySymbol doorType = doorTypes.First() as FamilySymbol;
    // 在墙上放三个门
    double x = 2, y = 2;
    for (int i = 0; i < 3; i++)
    {
        XYZ location = new XYZ(x, y, 0);
        FamilyInstance instance = document.Create.NewFamilyInstance(location, doorType, newWall, StructuralType.NonStructural);//创建窗户
        x += 3;
        y += 3;
    }
    return newWall;
}

```

### 1.1.3 窗户
 <img src="../img/101/Window.png" width="48" />

##### API-1：<font color=gray>(2016~2023)</font>
```CSharp 
 FamilyInstance NewFamilyInstance(
	XYZ location,
	FamilySymbol symbol,
	Element host,
	StructuralType structuralType
)
```

##### 示例
```CSharp
Wall CreateWallWithWindows(Autodesk.Revit.DB.Document document, Level level)
{
    // 创建一片墙
    // 构建一条墙的基线
    XYZ start = new XYZ(0, 0, 0);
    XYZ end = new XYZ(10, 10, 0);
    Line wallLine = Line.CreateBound(start, end);

    // 以基线的方式创建墙体
    Wall newWall = Wall.Create(document, wallLine, level.Id, true);

    // 找到一个窗户的族模型
    FilteredElementCollector winCollector = new FilteredElementCollector(document);
    IList<Element> windowTypes = winCollector.OfCategory(BuiltInCategory.OST_Windows).WhereElementIsElementType().ToElements();
    FamilySymbol winType = windowTypes.First() as FamilySymbol;
    // 在墙上放三个窗户
    double x = 2, y = 2, z = 2;
    for (int i = 0; i < 3; i++)
    {
        XYZ location = new XYZ(x, y, z);
        FamilyInstance instance = document.Create.NewFamilyInstance(location, winType, newWall, StructuralType.NonStructural);//创建窗户
        x += 3;
        y += 3;
    }
    return newWall;
}

```

### 1.1.4 构件 
<img src="../img/101/Component.png" width="48" />

##### API-1：<font color=gray>(2016~2023)</font>
```CSharp 
 FamilyInstance NewFamilyInstance(
	XYZ location,
	FamilySymbol symbol,
	Element host,
	StructuralType structuralType
)
```



